### ISSUE TITLE
Add way to disable printing of intro

### ISSUE THREAD

**Issue by bnason-nf** [doctest/doctest#181]
Hi @onqtam,

It would be nice if doctest had a way to disable printing the intro the same way you can disable printing the version, probably a "no-intro" option.

Thanks,
Benbuck

**Comment by onqtam** [comment]
@bnason-nf There will be something like that when I'm done with the [reporters](https://github.com/onqtam/doctest/issues/138) - there will be a quiet mode :)

no promises when I'll be able to get back to finishing that though...

**Comment by onqtam** [comment]
the no-version option is there only because of the tests of doctest - so that I don't change a bunch of .txt files in the repo when I bump the version up.

I could actually add this new option separately and reroute the no-version one to no-intro but I'm curious what your use case is - even if the entire intro is skipped you still get the report summary, right...?

**Comment by bnason-nf** [comment]
Hi @onqtam,

This is a trivial issue for me, it just would be nice if every run didn't say:

`[doctest] run with "--help" for options`

Because after the first time I already know about --help, but it's not worth a lot of trouble.

Thanks,
Benbuck

**Comment by onqtam** [comment]
30 months later - no intro implemented in the `dev` branch :)
