### ISSUE TITLE
vscode test explorer

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [doctest/doctest#303]
vscode has a [test explorer extension](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer&ssr=false). It would be nice to have a doctest adaptor for it.

**Comment by onqtam** [comment]
I'd be happy if someone does the integration :)
Currently I know only about [ReSharper C++](https://blog.jetbrains.com/rscpp/resharper-cpp-2019-1-responsive-better-unreal-engine-new-language-features/) (and [link 2](https://blog.jetbrains.com/rscpp/better-ways-testing-with-doctest/)) having doctest integration.

Since doctest is quite similar to Catch I guess it should be easy (I see the VSCode extension has support for Catch2). I just don't have the capacity to work on such things since I started my job...

**Comment by Mirko-von-Leipzig** [comment]
I'll take a look this week to see if I can make sense of the code.

**Comment by wilhem-meignan** [comment]
Hi,

There is some experimental support for doctest in the vscode-catch2-test-adapter Extension.

See: https://github.com/matepek/vscode-catch2-test-adapter/issues/143

**Comment by Trass3r** [comment]
Can be closed then.

**Comment by onqtam** [comment]
the vscode-catch2 test adapter should be enough. closing.
