### ISSUE TITLE
MESSAGE() accepts std::setw, but CHECK_MESSAGE() doesn't

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#323]
This code compiles:
```
MESSAGE(kernel_name << " check " << std::setw(4) << (i+1) << " failed.");
```
this code doesn't:
```
CHECK_MESSAGE(false, kernel_name << " check " << std::setw(4) << (i+1) << " failed.");
```
It gives me:
```
/path/to/doctest.h(1582): error: static assertion failed with "Cannot pass temporaries or rvalues
to the streaming operator because it caches pointers to the passed objects for lazy evaluation!"
```

* doctest version: **v2.3.0**
* Operating System: Devuan GNU/Linux 3.0
* Compiler+version: GCC 9.2.1

**Comment by onqtam** [comment]
```MESSAGE()``` and ```CHECK_MESSAGE``` are different - one is intended to always print, and the other only when the assert fails. That is why the one which is combined with an assert is implemented in terms of the ```INFO()``` logging facility, which has an optimization - it doesn't create the string until necessary (an assert later on fails). Due to this optimization rvalues aren't allowed.

Can you try saving the ```std::setw(4)``` into a local variable and then passing that ```lvalue``` (instead of the ```rvalue``` which it otherwise would be)?

**Comment by eyalroz** [comment]
If I save both `std::setw(4)` _and_ `i+1`, then `CHECK_MESSAGE()` works. But this is: (1.) Surprising, when you switch between the two, (2.) Surprising, since we're used to `<<` sequences being able to take temporaries/rvalue references - e.g. when we use ostreams.

**Comment by onqtam** [comment]
I agree with you... it should have been called ```CHECK_INFO()```. The use of the ```operator<<``` is questionable as well given the problem with rvalues... Perhaps the optimization altogether (because of which rvalues aren't allowed) isn't that much beneficial - the main reason was to have superb performance in hot loops with millions of asserts where the counter is being logged with ```INFO()``` - premature optimization - I doubt that has been the selling point of doctest :|

But I doubt I'm changing any of that anytime soon...

**Comment by cdeln** [comment]
Update on state of this issue. I believe this has been fixed at some point.
The following code compiles and runs fine for me

```cpp
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include <doctest/doctest.h>

TEST_CASE("323")
{
    int i = 1337;
    const std::string kernel_name = "abc";
    MESSAGE(             kernel_name << " check " << std::setw(4) << (i+1) << " failed.");
    CHECK_MESSAGE(false, kernel_name << " check " << std::setw(4) << (i+1) << " failed.");
}
```

Output

```console
[doctest] doctest version is "2.4.11"
[doctest] run with "--help" for options
===============================================================================
main.cpp:5:
TEST CASE:  323

main.cpp:9: MESSAGE: abc check     1338 failed.

main.cpp:10: ERROR: CHECK( false ) is NOT correct!
  values: CHECK( false )
  logged: abc check 1338 failed.

===============================================================================
[doctest] test cases: 1 | 0 passed | 1 failed | 0 skipped
[doctest] assertions: 1 | 0 passed | 1 failed |
[doctest] Status: FAILURE!
```

**Comment by eyalroz** [comment]
Ok, then closing. If I encounter this again I'll reopen. (Not actively working on my testing code right now.)

**Comment by onqtam** [comment]
this must have gotten fixed by accident when all asserts were switched to use a ```[&]``` capturing lambda

**Comment by cdeln** [comment]
Nice accident :D
