### ISSUE TITLE
Some applicable comparison operators not "picked up on" by WARNING/CHECK/REQUIRE

### ISSUE THREAD

**Issue by eyalroz** [doctest/doctest#349]
For some classes which don't have auto-generated comparison operators, and are within some deep namespace, it's possible that a comparison operator is available - via an `operator==` member and/or a global-namespace `operator==()` function - but without doctest picking up on it, and complaining, with `CHECK`/`WARNING`/`REQUIRE` macros, that a comparison op is unavailable. If I add an `operator==` in the class' own deep namespace (but out of the class), then it gets picked up.

I suspect this might have something to do with the way you decompose expressions in these kinds of macros, but I'm not sure.

I'm using v2.3.7, commit 932a2ca50666138256dae56fbb16db3b1cae133a from the master branch.

(Sorry for this bug report being a bit sketchy due to the lack of exact reproduction instructions.)

**Comment by deepbluev7** [comment]
I think this happens, because the comparison operator is neither defined in the namespace of the type being compared nor in the `doctest` namespace. This is an issue, because the comparison actually happens in the `doctest` namespace. Because of that, ADL can't find the comparison operator, since it only looks in the namespace of the type and in the `doctest` namespace. Maybe this could be worked around by actually defining the functions, that do the comparison, in the global namespace or the test namespace? Not sure, why a member operator wouldn't get picked up though. Here is a good blogpost summarzizing the adl rules: https://quuxplusone.github.io/blog/2019/04/26/what-is-adl/

**Comment by cdeln** [comment]
@Saalvage Does https://github.com/doctest/doctest/commit/a39ff191bf704d88c0d9f6afc224777e1f431139 fix this?

**Comment by eyalroz** [comment]
@cdeln : I don't know, but since I'm not actively experiencing this right now and could not provide a reproducible example, I'm closing for now. If I encounter this again I'll reopen.
