### ISSUE TITLE
Own repository

### ISSUE THREAD

**Issue by paulo-coutinho** [doctest/doctest#410]
Hi,

It is only my suggestion. 

Why not put this great framework on their own repository.

I think that it will be professional/elegant.

ex: github.com/doctest/doctest

What you think?

**Comment by onqtam** [comment]
Hi, and sorry for the late reply!

I've thought about making an organization for the project in order to make it more professional and to stimulate more contributions but I just haven't done it yet...

I just secured the [`doctest`](https://github.com/doctest) orgname - it was held by someone else but they were kind enough to give it to me :)

This hasn't been on my list of priorities, but it might happen soon.

**Comment by Calinou** [comment]
> I'm not sure if it will handle properly link redirects 

If you transfer the repository from the Settings tab, a redirect will be made automatically.

**Comment by onqtam** [comment]
It's done - https://github.com/doctest :)

This is the accompanying announcement: https://github.com/doctest/doctest/issues/554
