### ISSUE TITLE
How to call individual tests and how to pass runtime data to test?

### ISSUE THREAD

**Issue by gamagan** [doctest/doctest#455]
I'm trying to use Doctest to test a 3D renderer. I would like to set it up such that each renderer frame runs 1 test-case. The renderer would write frame data to memory, including image data, and the test assertions would then compare that frame data with known good values.

How can I setup Doctest to run one test at a time, and how can I pass runtime data to the test?

Thanks

### Extra information
* doctest version: v2.4.4
* Operating System: Window's 10
* Compiler+version: MSVC 2019, Latest

**Comment by onqtam** [comment]
I guess you need to initialize the renderer once and then you want to check that a sequence of rendered frames (based on some pre-determined animated scene) match pre-rendered images?

In that case why not simply have 1 test case for each scene and just loop over the frames and assert on each frame that the result matches the pre-rendered images?

**Comment by onqtam** [comment]
I don't understand exactly what you mean by `one test at a time` and why you would want that. Can't you just have separate test cases for the separate scenes where you assert that the results match, and in the case of animated scenes (with multiple frames) simply use a loop in the test case to assert for each frame?

You can also invoke the doctest binary with [command line filters](https://github.com/onqtam/doctest/blob/master/doc/markdown/commandline.md) and you can explicitly make doctest execute 1 specific test case by specifying its name with `--test-case=<exact_name_of_test_case>`.

Regarding runtime data - you can implement [your own `main()`](https://github.com/onqtam/doctest/blob/master/doc/markdown/main.md) and perhaps do some custom command-line parsing of your own so that you set some global variable for the test cases to access.

**Comment by gamagan** [comment]
By one test-case at a time, I mean that the Renderer would render one frame, then that frame would be tested against some known value(s), and then the Renderer would render the next frame. In other words, the renderer wouldn't render all frames at once, then then compare all the results at one. The reason for wanting one frame at a time is that I can put the frame creation and frame testing data into different test-cases, and this will then serve as a type of documentation for the various features.

So far, I started working on a solution like what you mentioned: use `--test-case=` to filter tests, and using globals to pass data.  I'm calling Context::run() once per test, during program execution. The test-cases are executed(optionally) as part of normal program run; that is, the test-cases are embedded within the renderer program, it's not a separate test binary.

One function that would help is to be able to enumerate the test-case names, before calling `Context::run()`. That way, I don't have to keep a manual test names in a list.

This other function is minor: `Calling Context::run()` multiple times creates multiple stats output. If possible, it would be nice if `Context:run()` would take an argument to tell it to display some abbreviated output for non-last tests, and then output the full stats for the final test. This is just a nice to have, though.

**Comment by onqtam** [comment]
In order to enumerate the test case names, you could call the test binary once with `--list-test-cases` and then use the outputted list (after trimming the first 2 and last 2 rows). Others have also requested to enumerate the list of test cases in C++ before but I haven't exposed that functionality yet - have a look at this issue and where I mention `getRegisteredTests`: https://github.com/onqtam/doctest/issues/184

Combining the results from multiple calls to `Context::run()` isn't very straightforward... (well... you could theoretically do it with quite a bit of code and writing your own [reporter](https://github.com/onqtam/doctest/blob/master/doc/markdown/reporters.md))

Have you looked at subcases? https://github.com/onqtam/doctest/blob/master/doc/markdown/tutorial.md
You could have 1 test case with multiple subcases where the first subcases generate the frame data and the other subcases test the frame data. Perhaps you don't need to execute the binary many times but could implement everything in test cases & subcases inside of the C++?

**Comment by gamagan** [comment]
Thanks for the pointers to other issue tickets.

The Renderer is hardware based. I have to issue commands to the GPU to draw the frame, and then get the result in the next iteration, because it takes some time for the GPU to complete the frame. Thus, I have to call the TestCase once to setup the frame to be rendered; then the Renderer issues the commands to the GPU and renders the frame; finally, I call the TestCase, again, to verify the created frame data. So, something like Subcases wouldn't work for my usecase.

**Comment by YarikTH** [comment]
Normally graphics API supports [glFlush](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glFlush.xml) command analog that allows to wait for all GPU commands to be executed. So you can do something straightforward like:

```cpp
TEST_CASE("TestRenderer")
{
     MyRenderer r;
     while( !r.done() )
     {
          r.drawFrame();
          r.flush();
          CHECK(/*something*/);
     }
}
```

Anyway, passing runtime data and executing specific tests in a specific order with some user code between, sounds like the wrong way to do things. Maybe it's better to write your own testing loop and use doctest just as an assertion library.

**Comment by gamagan** [comment]
I don't need this anymore. Closing this issue.
