### ISSUE TITLE
toString can call existing user-defined toString through ADL incorrectly

### ISSUE THREAD

**Issue by zeux** [doctest/doctest#508]
## Description

In existing user bases, `toString` may already be declared for some existing types - with a different return type. In our case, we had a version `std::string toString(Foo*)` - this doesn't work in two contexts:

1. When comparing for equality e.g. `CHECK_NE(ptr, nullptr);`, two different toString overloads get called in `stringifyBinaryExpr` - Foo* gets a std::string result, and nullptr gets a doctest::String result. Concatenation fails since the types are distinct.
2. In a similar context, when using a decomposable check, e.g. `CHECK(ptr != nullptr);`, `Expression_lhs` calls toString on the input type, gets a std::string, and proceeds to pass it into doctest::Result (which fails since it contains `doctest::String` instead.

I understand that the fact that toString is picked via ADL is a feature, but this means that codebase under test needs to be redesigned to use a different name than toString which seems suboptimal.

For us any solution that makes these checks compile would work:

- Handle cases when toString returns a std::string by wrapping the call in an extra conversion function (that has overloads for `std::string`; maybe `toString(toString(v))`? :)
- Proxy the call through some helper that validates whether toString impl returns a doctest::String (unsure how...)
- Provide a config option that disables the use of ADL by qualifying the toString calls with `doctest::` (we use operator<< to provide custom type display)

Please let me know if I can help implement one of these, happy to submit a PR.

### Steps to reproduce

https://gcc.godbolt.org/z/TYfKrKG5M

```c++
namespace App {
    struct Foo {};
    std::string toString(Foo*) { return "Foo"; }
}

TEST_CASE("test") {
    App::Foo foo;
    CHECK(&foo != nullptr);
    CHECK_NE(&foo, nullptr);
    CHECK(&foo);
}
```

### Extra information
* doctest version: **2.4.6**
* Compiler+version: **MSVC 2019**

**Comment by onqtam** [comment]
Sorry for the late reply, but you know how it goes - focus on the fluff and delay whatever requires any thought!

Option 1 is tricky because it would require either including `<string>` (which might be inevitable and maybe delaying that is wrong - maybe should remove `doctest::String altogether...`) or forward-declaring it which would be hard/nasty, so I'd say a PR with option 3 would be best if there aren't other ways to fix this. There's [`another issue regarding toString`](https://github.com/doctest/doctest/issues/420) - not sure if it's related.

On a side note, I'm stepping away from the development of doctest - [this is the announcement saying why and how it would go down](https://github.com/doctest/doctest/issues/554), so the project is looking for maintainers. The work isn't too much so if you have anyone in mind... :)

**Comment by Saalvage** [comment]
We're forward declaring `std::string` anyways at this point. So why not go for 1. :)
I guess one concern would be people returning their own string class from `toString`.. I'll give this some more thought, the option of having `toString` called twice would definitely solve it, but we already have too many config options!
#639

**Comment by Saalvage** [comment]
Ok, so other compilers do not like having `std::string` forward declared! So we'll go with the likely superior option of allowing customization of the stringification method via macros, allowing for people to use double stringification if they so choose! I'll get to this tomorrow.

**Comment by Saalvage** [comment]
Fixed in dev!

**Comment by zeux** [comment]
Just want to confirm that DOCTEST_CONFIG_DOUBLE_STRINGIFY solves this for us, thank you for the fix!
