### ISSUE TITLE
MSVC warnings leak through when using the library as a single header with /Wall

### ISSUE THREAD

**Issue by Saalvage** [doctest/doctest#565]
## Description
doctest seemingly has a list of 4 warnings that "should be disabled globally", however, these warnings only ever appear to be disabled when building via cmake, which you obviously don't use when utilizing the single header feature. At least for my compiler and a minimal project this leads to warning C4514 being thrown around a whole bunch.

I'm not exactly sure on how this should be adressed, which is why I raised this issue instead of making a PR, I'd imagine just adding the 4 warnings at the top of the all-encompasing warning push should be enough. If this is indeed the case I'll happily craft up a PR if this isn't considered too trivial.

### Steps to reproduce
Create a new project, set the warning level to /Wall, include the `doctest.h` header in a source file and compile.

### Extra information
* doctest version: 68fab34c (dev head at the time of posting)
* Operating System: Windows 10 Pro 19043
* Compiler+version: MSVC 22 17.0.2

**Comment by onqtam** [comment]
I had a period where I was trying to make it work with `/Wall` but it was very impractical - nobody in the world really uses that flag - saying it's too noisy is an understatement.

4514 is more of a diagnostic - any real world project with 100k LOC would produce thousands of it.

So that's why a few warnings are explicitly disabled in `common.cmake` and 4514 is one of them - with `/wd4514`. I don't think the framework should disable it globally - better leave that flexibility to end users who dare mess with 4514 :)

**Comment by Saalvage** [comment]
What you're saying is definitely true, especially since MSVC's STL implementation itself is throwing out warnings left and right when using /Wall!
But I think I might've miscommunicated a bit, I'd like for those flags to be added to the warnings that get pushed to be disabled at the start and popped again at the end of the header, so they don't show up in projects using the header only version of the library.

**Comment by onqtam** [comment]
I had tried that, but in order for the builds to pass I had to also introduce this `DOCTEST_MAKE_STD_HEADERS_CLEAN_FROM_WARNINGS_ON_WALL_BEGIN` macro which suppresses a bunch of other warnings that are beyond `/W4` and mostly present in `/Wall`:
https://github.com/doctest/doctest/blob/2.4.6/doctest/doctest.h#L201

And I used it across the examples which get built with `/Wall` in the global flags - like this:
https://github.com/doctest/doctest/blob/2.4.6/examples/all_features/stringification.cpp#L5-L10

But as far as I remember, those 4 other warnings that I've left out couldn't simply be added even to `DOCTEST_MAKE_STD_HEADERS_CLEAN_FROM_WARNINGS_ON_WALL_BEGIN` (in addition to push/pop for the header itself) because they would still get triggered for most (every?) function being used anywhere in the examples - as diagnostics for SEH/inlining by the compiler for example - overly verbose. I don't think it's worth it and that anyone uses them

**Comment by Saalvage** [comment]
I might be missing something obvious here, in which case I'm sorry, but I'll just describe how doctest behaves on `/Wall` with my project:
By default, it throws a whole bunch of `C4514` warnings.
If I simply insert `4514` along with the others here: https://github.com/doctest/doctest/blob/4d8716f1efc1d14aa736ef52ee727bd4204f4c40/doctest/doctest.h#L166
All of those warnings disappear and nothing gets thrown from doctest at all.

I'm simply wondering if there's anything that speaks against simply including all 4 of those warnings at the location I linked, since it seemingly seems to stop doctest from throwing anything, even at `/Wall`!

**Comment by onqtam** [comment]
Actually, there is indeed 0 harm in including them where you've suggested if it works in your setup - PR is welcome!

I'm just skeptical that they could be enabled on the examples folder of doctest without adding a bunch more annotations there - meaning no longer disabling them in `common.cmake`. PR is welcome!

**Comment by onqtam** [comment]
closing this since the PR is merged now
