### ISSUE TITLE
Local structured bindings cannot be used in CHECK macros (since 2.4.8)

### ISSUE THREAD

**Issue by pragmaxwell** [doctest/doctest#647]
## Description

Referencing [C++17 structured bindings](https://en.cppreference.com/w/cpp/language/structured_binding) in CHECK macros fails to compile.

### Steps to reproduce

The test below compiles in doctest 2.4.6 and fails in 2.4.8.

```cpp
TEST_CASE("broken") {
    auto [one, two] = std::tuple<int, int>{1, 2};
    CHECK(one == 1);
    CHECK_EQ(one, 1);
    // example error: Reference to local binding 'one' declared in enclosing function 'tests::DOCTEST_ANON_SUITE_2::DOCTEST_ANON_FUNC_3
}
```

### Extra information
* doctest version: **v2.4.8**
* Operating System: Windows 10
* Compiler+version: clang++ 12.0.1

FWIW it compiles fine in MSVC 19.29.30139.0

I'm guessing something change recently where SUBCASES or perhaps the CHECK macros capture params in a lambda, which is not supported with structured bindings (until c++20, see [notes section](https://en.cppreference.com/w/cpp/language/structured_binding)).

### Workaround

In case anyone needs it:

```cpp
TEST_CASE("workaround") {
    auto tuple = std::tuple<int, int>{1, 2};
    CHECK(std::get<0>(tuple) == 1);
    CHECK_EQ(std::get<0>(tuple), 1);
}
```

**Comment by Saalvage** [comment]
This has been fixed in dev.

Previously assertion macros were implemented via a do-while loop, this has been changed to be a lambda in order to support returning values to the call site (`if (CHECK(...))`). As you've mentioned this doesn't work for structured bindings, which is why this, evidently breaking, change is being reverted in 2.4.9, which is (long over)due to be released this month. The feature of returning values from assertions has been put behind the [`DOCTEST_CONFIG_ASSERTS_RETURN_VALUES`](https://github.com/doctest/doctest/blob/dev/doc/markdown/configuration.md#doctest_config_asserts_return_values) option.

I'm sorry for the inconvenience!

**Comment by pragmaxwell** [comment]
Great thank you! I'll pin @ 2.4.6 for now and update when 2.4.9 is out, cheers.
