### ISSUE TITLE
Help needed with the builds

### ISSUE THREAD

**Issue by onqtam** [doctest/doctest#733]
Currently, one of the reasons version 2.4.10 is being delayed is the failing builds in the `dev` branch

Here's a recent run of GitHub Actions on another branch from a few days ago:
https://github.com/doctest/doctest/actions/runs/3855883199

Most of the builds fail at the install step - need help with that. This is the build config:
https://github.com/doctest/doctest/blob/dev/.github/workflows/main.yml

The ones that fail at the build step due to C++-ish issues will be fixed after that.

**Comment by onqtam** [comment]
reopening because there are still problems with clang:
https://github.com/doctest/doctest/actions/runs/4285074449

**Comment by navinp0304** [comment]
It looks like valgrind is causing the following error 
### unhandled dwarf2 abbrev form code 0x25

Valgrind: debuginfo reader: Possibly corrupted debuginfo file.
Valgrind: debuginfo reader: Possibly corrupted debuginfo file.

The fix is to compile with -gdwarf-4 in CXXFLAGS when build type is Debug. I tried compiling with gdwarf-4 and it fixes the valgrind issue and all tests pass.

https://bugzilla.mozilla.org/show_bug.cgi?id=1758782
