### ISSUE TITLE
Discord invite link doesn't work

### ISSUE THREAD

**Issue by jokervTv** [doctest/doctest#793]
Discord invite link in README not working.

**Comment by Saalvage** [comment]
The Discord server doesn't seem to exist anymore, I'm not sure why. @onqtam any insight?

**Comment by onqtam** [comment]
I deleted the server as I thought it was unnecessary - very low activity on both ends (users and lib maintainers). GitHub issues, PRs & the relatively recent discussions should be enough for doctest to move forward.

The broken discord link is fixed in the dev branch & will get merged in master at some point.
